### ISSUE TITLE
[ERROR] Metadata version mismatch for module

### ISSUE THREAD

**Issue by igoventura** [aspnetboilerplate/module-zero-core-template#141] opened 2017-11-17 17:58 UTC
Hello,

I'm trying to create a project using this template but when I run ```npm start``` or ```npm run hmr``` return this error:

```
ERROR in Error: Metadata version mismatch for module D:/Projetos/DNA.DFMedicaBR/3.3.2/angular/node_modules/abp-ng2-module/node_modules/@angular/http/http.d.ts, found version 4,
expected 3, resolving symbol ABP_HTTP_PROVIDER in D:/Projetos/DNA.DFMedicaBR/3.3.2/angular/node_modules/abp-ng2-module/src/abp.module.ts, resolving symbol RootModule in
D:/Projetos/DNA.DFMedicaBR/3.3.2/angular/src/root.module.ts, resolving symbol RootModule in D:/Projetos/DNA.DFMedicaBR/3.3.2/angular/src/root.module.ts
    at syntaxError (D:\Projetos\DNA.DFMedicaBR\3.3.2\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (D:\Projetos\DNA.DFMedicaBR\3.3.2\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (D:\Projetos\DNA.DFMedicaBR\3.3.2\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13) 
	at StaticReflector.annotations (D:\Projetos\DNA.DFMedicaBR\3.3.2\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41) 
	at _getNgModuleMetadata (D:\Projetos\DNA.DFMedicaBR\3.3.2\angular\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (D:\Projetos\DNA.DFMedicaBR\3.3.2\angular\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (D:\Projetos\DNA.DFMedicaBR\3.3.2\angular\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22) 
	at Function.NgTools_InternalApi_NG_2.listLazyRoutes
	(D:\Projetos\DNA.DFMedicaBR\3.3.2\angular\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)at AotPlugin._getLazyRoutesFromNgtools
	(D:\Projetos\DNA.DFMedicaBR\3.3.2\angular\node_modules\@ngtools\webpack\src\plugin.js:241:66)
	at _donePromise.Promise.resolve.then.then.then.then.then 
	(D:\Projetos\DNA.DFMedicaBR\3.3.2\angular\node_modules\@ngtools\webpack\src\plugin.js:495:24)
	at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ismcagdas** [comment] 2017-11-17 18:02
Can you remove node_modules folder and try to install dependencies using yarn ?

**Comment by abdo38013** [comment] 2017-11-19 11:50
Hello @ismcagdas , 
I removed the node modules so many times but and installed it but i got the same error and I tried to install with yarn also but it gave me an error during installation.
`"error An unexpected error occurred: "https://registry.yarnpkg.com/@angular/animations/-/animations-4.3.6.tgz: self signed certificate in certificate chain"."`

**Comment by ismcagdas** [comment] 2017-11-19 19:40
@abdo38013 what is your global yarn version ? This seems like a yarn issue. My version is 1.3.2.

**Comment by abdo38013** [comment] 2017-11-20 09:45
@ismcagdas 
my version is 1.3.2 also.

**Comment by abdo38013** [comment] 2017-11-20 09:55
Hello @ismcagdas my problem is for the yarn that i was under a proxy and I solved it thanks.
but what about the second issue of the mismatch version using npm

**Comment by abdo38013** [comment] 2017-11-20 10:04
Hello @ismcagdas,
After I installed the packages using yarn I got another error in abp-ng2-module
`ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in D:/Boilerplate Master/angular/node_modules/abp-ng2-module/node_modules/@angular/core/core.d.ts, resolving symbol AbpModule in D:/Boilerplate Master/angular/node_modules/abp-ng2-module/src/abp.module.ts, resolving symbol AbpModule in D:/Boilerplate Master/angular/node_modules/abp-ng2-module/src/abp.module.ts`

**Comment by ismcagdas** [comment] 2017-11-20 10:19
@abdo38013 can you check which version of abp-ng2-module is installed ?

**Comment by abdo38013** [comment] 2017-11-20 10:26
@ismcagdas 1.2.0

**Comment by abdo38013** [comment] 2017-11-20 12:40
@ismcagdas  ok i found the problem 
when i ran npm install or yarn install, it's install the latest version of each package 
the problem is it's installs @angular/http version 4.4.6 and abp-ng2-module version 1.3,
I tried to downgrade each package of them and installed 
@angular/http version 4.3.6 and abp-ng2-module version 1.2 
and everything went to work.

**Comment by igoventura** [comment] 2017-11-20 12:54
@abdo38013 version 4.4.6 of angular? The version of angular who is installing is 5.0.0 and abp-ng2-module version 1.2.4

**Comment by abdo38013** [comment] 2017-11-20 13:54
@igoventura in my case when i ran npm install 
it installed angular 4.4.6 and abp 1.3 
and this logical because of "^" in package.json

**Comment by ismcagdas** [comment] 2017-11-21 06:03
@abdo38013 you are right, npm install acts like that. 
We are using and suggesting yarn because of prevent such problems.

We will upgrade to angular 5 in a short time.

**Closed by ismcagdas** 2017-11-21 06:03 UTC
