### ISSUE TITLE
Null Reference when using INotificationPublisher PublishAsync

### ISSUE THREAD

**Issue by leecannon** [aspnetboilerplate/module-zero-core-template#236] opened 2018-05-12 21:55 UTC
I am recieving a null reference exception when attempting to publish a notification.

## Steps to reproduce:
1. Download the startup template with these settings:
    - ASP.NET Core 2.X
    - .NET Core (Cross Platform)
    - Angular
    - Include login, etc
    - Both stable and not stable are the same version (as of 12th May 2018)
2. Open 3.6.0\aspnet-core\<Project>.sln in Visual Studio 15.7.1
3. Set startup project to Web.Host
4. In package manager console change default project to EntityFrameworkCore, run `Update-Database`
5. Make NotificationAppService class in 'Application' - [gist with code](https://gist.github.com/leecannon/d7c8c9081320d8fedcbbe87b1cd3f30c)
6. Run Web.Host in debug
7. Use swagger to execute the `MessageTest` end point

[Stack Trace](https://gist.github.com/leecannon/8f397e308fe60fce67d1f198d98d0816)

**Comment by ismcagdas** [comment] 2018-05-13 10:59
@leecannon could you upgrade to ABP nuget packages to 3.6.1 and try again ?

**Comment by leecannon** [comment] 2018-05-13 12:48
Before step 4 in the above updated all packages in the solution except left 'Swashbuckle.AspNetCore' at version 1.2.0

Same error - [Stack](https://gist.github.com/leecannon/ebb08908e370309d90518746560aa8ae)

**Comment by acjh** [comment] 2018-05-13 15:34
Duplicate of aspnetboilerplate/aspnetboilerplate#3124

**Closed** 2018-06-23 15:00 UTC
