### ISSUE TITLE
Problem with Asp.net core 2.0

### ISSUE THREAD

**Issue by Gardens18** [aspnetboilerplate/module-zero-core-template#312] opened 2018-07-28 06:37 UTC
I donwloaded the free version to get started with the boilerplate but in the organization we have Core 2.0 not 2.1 , so getting errors. so could you provide the version works with 2.0

**Comment by Gardens18** [comment] 2018-07-28 06:52
Your Abp package version - **3.9.0**
Your base framework: .Net Core - **2.0**
Exception message and stack trace if available.
**Severity	Code	Description	Project	File	Line	Suppression State
Error	The current .NET SDK does not support targeting .NET Core 2.1. Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1.	ISAS.Migrator	C:\Program Files\dotnet\sdk\2.1.200\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets 135**

**Comment by acjh** [comment] 2018-07-28 07:47
Duplicate of https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3690#issuecomment-408589966. Please don't spam.

**Closed by acjh** 2018-07-28 07:47 UTC
