### ISSUE TITLE
Unexpected authenticateResult!

### ISSUE THREAD

**Issue by Donistivanov** [aspnetboilerplate/module-zero-core-template#234] opened 2018-05-10 18:53 UTC
I've been trying to upgrade everything to the latest packages I've been running into issues the one I can't seem to shake it is being unable to log in

I added some console.logs to `login.service.ts`:
```
    authenticate(finallyCallback?: () => void): void {
        finallyCallback = finallyCallback || (() => { });

        this._tokenAuthService
            .authenticate(this.authenticateModel)
            .finally(finallyCallback)
            .subscribe((result: AuthenticateResultModel) => {
                console.log("1")
                console.log(result)
                this.processAuthenticateResult(result);
            });
    }

    private processAuthenticateResult(authenticateResult: AuthenticateResultModel) {
        this.authenticateResult = authenticateResult;

        console.log("2")
        console.log(authenticateResult)
        if (authenticateResult.accessToken) {
            //Successfully logged in
            this.login(authenticateResult.accessToken, authenticateResult.encryptedAccessToken, authenticateResult.expireInSeconds, this.rememberMe);

        } else {
            //Unexpected result!
            this._logService.warn('Unexpected authenticateResult!');
            this._router.navigate(['account/login']);
        }
    }
```
And I get 

![image](https://user-images.githubusercontent.com/12190565/39887717-eda12520-5460-11e8-9241-e13371374add.png)

I also have my packages up to date as suggested here: https://github.com/aspnetboilerplate/module-zero-core-template/issues/214

angular is on version 5.2.9
"abp-ng2-module": "^2.1.0",
"abp-web-resources": "^3.5.0",

**Comment by ismcagdas** [comment] 2018-05-10 19:05
@Donistivanov could you compare your service.config.nswag with this one https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/angular/nswag/service.config.nswag ?

Can you see a valid response from server on your browser's network tab ?

**Comment by Donistivanov** [comment] 2018-05-10 20:04
Part of what I did was upgrade nswag, but I went through the steps one more time to be sure.
Everything is a one-to-one match except the port which the back-end is serving on.

Then I ran `refresh.bat` once the server was running.

Then I npm installed again. That gave me some warnings
![image](https://user-images.githubusercontent.com/12190565/39891339-411bc1a6-546b-11e8-89a3-0d9fa0137054.png)

I am not sure if this is relevant but the first time I `ng serve` I get the following error which I fix by deleting the node_modules found in the abp-ng-module package:
![image](https://user-images.githubusercontent.com/12190565/39891286-22462df2-546b-11e8-87cd-545b9a9fc142.png)

Then on the second `ng serve` the log in page displays and I can try to use it:
![image](https://user-images.githubusercontent.com/12190565/39891413-829936cc-546b-11e8-9ff0-4783e0a56626.png)

**Comment by ismcagdas** [comment] 2018-05-11 06:10
@Donistivanov does it always fail on the first attempt to run angular app and works on second attempt ? This seems like an Angular problem.

**Comment by Donistivanov** [comment] 2018-05-11 13:13
I do not know what you mean by works, but the first time the login screen does not load at all because of something to do with packages, I guess. By extension, I cannot log in.

But on the second time the login screen shows, but I still cannot log in with the console logs from my very first picture

**Comment by Donistivanov** [comment] 2018-05-16 14:01
I haven't had much luck and I think I am either going to restart from a new project or try to upgrade to 6.0 by watching the steps that will close the following issue; https://github.com/aspnetboilerplate/module-zero-core-template/issues/232

**Comment by JigneshPatel04** [comment] 2018-06-08 11:44
Do you resolve it? @Donistivanov

**Comment by Donistivanov** [comment] 2018-06-25 23:46
@JigneshPatel04 No. I've been thinking about a new approach to better suit the use case for the software I'll make so I don't think I'll be going back much to the project code this question was for.

**Comment by daniel-luberda** [comment] 2018-08-12 11:11
May be related to this: https://github.com/aspnetboilerplate/module-zero-core-template/issues/318

**Comment by ismcagdas** [comment] 2018-08-12 20:15
Closing since we are not able to reproduce the problem. May be related to https://github.com/aspnetboilerplate/module-zero-core-template/issues/318.

**Closed by ismcagdas** 2018-08-12 20:15 UTC
