### ISSUE TITLE
App.test.tsx test failed in Reactjs

### ISSUE THREAD

**Issue by Sunildass** [aspnetboilerplate/module-zero-core-template#409] opened 2019-02-15 10:05 UTC
App.test.tsx test fails while using jest. 

Please find the attachment for reference. 

![testerror](https://user-images.githubusercontent.com/30902263/52849734-a8ebc080-3109-11e9-8f88-d99cd8d8304f.png)

Below is the code for App.test.tsx

import * as React from 'react';
import * as ReactDOM from 'react-dom';
import App from './App';

it('renders without crashing', () => {
  
  const div = document.createElement('div');
  ReactDOM.render(<App  />, div);
  ReactDOM.unmountComponentAtNode(div);
});

**Comment by ismcagdas** [comment] 2019-02-15 13:43
duplicate of https://github.com/aspnetboilerplate/module-zero-core-template/issues/412

**Closed by ismcagdas** 2019-02-15 13:43 UTC
